---
- name: Install MariaDB
  dnf:
    name: mariadb-server
    state: present

- name: Start MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Allow MySQL firewall
  firewalld:
    service: mysql
    permanent: yes
    state: enabled
    immediate: yes
