---
- name: Configure firewall
  hosts: webservers
  become: yes

  tasks:
    - name: Install firewalld
      dnf:
        name: firewalld
        state: present

    - name: Start firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Allow HTTP
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
